//
// Created by eduard on 4/5/24.
//

#ifndef PROIECT_ALG_GENETICI_QUADRATICFUNCTION_H
#define PROIECT_ALG_GENETICI_QUADRATICFUNCTION_H


class QuadraticFunction {

};


#endif //PROIECT_ALG_GENETICI_QUADRATICFUNCTION_H
